---
name: Coverage

"on":
  push:
    branches:
      - master
  pull_request: {}

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Test coverage
        run: npm run cover

      - name: Notify Microsoft Teams
        uses: Skitionek/notify-microsoft-teams@ffb09c64e82bfa4859ab51c48830bb3483067bbf
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
