---
name: Coverage

"on":
  push:
    branches:
      - master
  pull_request: {}

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Test coverage
        run: npm run cover

      - name: Notify Microsoft Teams
        uses: Skitionek/notify-microsoft-teams@40873aa494cbb4fd3fea7773973df17d1358e48d
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
