---
name: Unit tests

"on":
  push:
    branches:
      - master
  pull_request: {}

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:only

      - name: Notify Microsoft Teams
        uses: Skitionek/notify-microsoft-teams@e27fb650a87cdbde20b7dffaf4f05b56b0141e1e
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
